#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MediBook.Client.Android.Resource", IsApplication=true)]

namespace MediBook.Client.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Gcm.Client.Resource.String.library_name = global::MediBook.Client.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05003d
			public const int AliceBlue = 2131034173;
			
			// aapt resource value: 0x7f050033
			public const int AntiqueWhite = 2131034163;
			
			// aapt resource value: 0x7f05008d
			public const int Aqua = 2131034253;
			
			// aapt resource value: 0x7f050072
			public const int Aquamarine = 2131034226;
			
			// aapt resource value: 0x7f05003b
			public const int Azure = 2131034171;
			
			// aapt resource value: 0x7f050038
			public const int Beige = 2131034168;
			
			// aapt resource value: 0x7f05001e
			public const int Bisque = 2131034142;
			
			// aapt resource value: 0x7f05009c
			public const int Black = 2131034268;
			
			// aapt resource value: 0x7f05001c
			public const int BlanchedAlmond = 2131034140;
			
			// aapt resource value: 0x7f050098
			public const int Blue = 2131034264;
			
			// aapt resource value: 0x7f05006b
			public const int BlueViolet = 2131034219;
			
			// aapt resource value: 0x7f05005f
			public const int Brown = 2131034207;
			
			// aapt resource value: 0x7f050045
			public const int BurlyWood = 2131034181;
			
			// aapt resource value: 0x7f05007d
			public const int CadetBlue = 2131034237;
			
			// aapt resource value: 0x7f050073
			public const int Chartreuse = 2131034227;
			
			// aapt resource value: 0x7f05004f
			public const int Chocolate = 2131034191;
			
			// aapt resource value: 0x7f050028
			public const int Coral = 2131034152;
			
			// aapt resource value: 0x7f05007c
			public const int CornflowerBlue = 2131034236;
			
			// aapt resource value: 0x7f050018
			public const int Cornsilk = 2131034136;
			
			// aapt resource value: 0x7f050048
			public const int Crimson = 2131034184;
			
			// aapt resource value: 0x7f05008e
			public const int Cyan = 2131034254;
			
			// aapt resource value: 0x7f05009a
			public const int DarkBlue = 2131034266;
			
			// aapt resource value: 0x7f050094
			public const int DarkCyan = 2131034260;
			
			// aapt resource value: 0x7f050057
			public const int DarkGoldenrod = 2131034199;
			
			// aapt resource value: 0x7f05005e
			public const int DarkGray = 2131034206;
			
			// aapt resource value: 0x7f050097
			public const int DarkGreen = 2131034263;
			
			// aapt resource value: 0x7f050054
			public const int DarkKhaki = 2131034196;
			
			// aapt resource value: 0x7f050069
			public const int DarkMagenta = 2131034217;
			
			// aapt resource value: 0x7f05007e
			public const int DarkOliveGreen = 2131034238;
			
			// aapt resource value: 0x7f050027
			public const int DarkOrange = 2131034151;
			
			// aapt resource value: 0x7f050062
			public const int DarkOrchid = 2131034210;
			
			// aapt resource value: 0x7f05006a
			public const int DarkRed = 2131034218;
			
			// aapt resource value: 0x7f050042
			public const int DarkSalmon = 2131034178;
			
			// aapt resource value: 0x7f050067
			public const int DarkSeaGreen = 2131034215;
			
			// aapt resource value: 0x7f050081
			public const int DarkSlateBlue = 2131034241;
			
			// aapt resource value: 0x7f050087
			public const int DarkSlateGray = 2131034247;
			
			// aapt resource value: 0x7f050092
			public const int DarkTurquoise = 2131034258;
			
			// aapt resource value: 0x7f050064
			public const int DarkViolet = 2131034212;
			
			// aapt resource value: 0x7f05002c
			public const int DeepPink = 2131034156;
			
			// aapt resource value: 0x7f050093
			public const int DeepSkyBlue = 2131034259;
			
			// aapt resource value: 0x7f05007a
			public const int DimGray = 2131034234;
			
			// aapt resource value: 0x7f05008b
			public const int DodgerBlue = 2131034251;
			
			// aapt resource value: 0x7f050058
			public const int FireBrick = 2131034200;
			
			// aapt resource value: 0x7f050016
			public const int FloralWhite = 2131034134;
			
			// aapt resource value: 0x7f050089
			public const int ForestGreen = 2131034249;
			
			// aapt resource value: 0x7f05002d
			public const int Fuchsia = 2131034157;
			
			// aapt resource value: 0x7f050047
			public const int Gainsboro = 2131034183;
			
			// aapt resource value: 0x7f050035
			public const int GhostWhite = 2131034165;
			
			// aapt resource value: 0x7f050022
			public const int Gold = 2131034146;
			
			// aapt resource value: 0x7f05004a
			public const int Goldenrod = 2131034186;
			
			// aapt resource value: 0x7f05006e
			public const int Gray = 2131034222;
			
			// aapt resource value: 0x7f050096
			public const int Green = 2131034262;
			
			// aapt resource value: 0x7f05005c
			public const int GreenYellow = 2131034204;
			
			// aapt resource value: 0x7f05003c
			public const int Honeydew = 2131034172;
			
			// aapt resource value: 0x7f050029
			public const int HotPink = 2131034153;
			
			// aapt resource value: 0x7f050051
			public const int IndianRed = 2131034193;
			
			// aapt resource value: 0x7f05007f
			public const int Indigo = 2131034239;
			
			// aapt resource value: 0x7f050012
			public const int Ivory = 2131034130;
			
			// aapt resource value: 0x7f05003e
			public const int Khaki = 2131034174;
			
			// aapt resource value: 0x7f050043
			public const int Lavender = 2131034179;
			
			// aapt resource value: 0x7f05001a
			public const int LavenderBlush = 2131034138;
			
			// aapt resource value: 0x7f050074
			public const int LawnGreen = 2131034228;
			
			// aapt resource value: 0x7f050017
			public const int LemonChiffon = 2131034135;
			
			// aapt resource value: 0x7f05005d
			public const int LightBlue = 2131034205;
			
			// aapt resource value: 0x7f05003f
			public const int LightCoral = 2131034175;
			
			// aapt resource value: 0x7f050044
			public const int LightCyan = 2131034180;
			
			// aapt resource value: 0x7f050031
			public const int LightGoldenrodYellow = 2131034161;
			
			// aapt resource value: 0x7f050066
			public const int LightGreen = 2131034214;
			
			// aapt resource value: 0x7f05004d
			public const int LightGrey = 2131034189;
			
			// aapt resource value: 0x7f050024
			public const int LightPink = 2131034148;
			
			// aapt resource value: 0x7f050026
			public const int LightSalmon = 2131034150;
			
			// aapt resource value: 0x7f05008a
			public const int LightSeaGreen = 2131034250;
			
			// aapt resource value: 0x7f05006c
			public const int LightSkyBlue = 2131034220;
			
			// aapt resource value: 0x7f050076
			public const int LightSlateGray = 2131034230;
			
			// aapt resource value: 0x7f05005a
			public const int LightSteelBlue = 2131034202;
			
			// aapt resource value: 0x7f050013
			public const int LightYellow = 2131034131;
			
			// aapt resource value: 0x7f050090
			public const int Lime = 2131034256;
			
			// aapt resource value: 0x7f050086
			public const int LimeGreen = 2131034246;
			
			// aapt resource value: 0x7f050032
			public const int Linen = 2131034162;
			
			// aapt resource value: 0x7f05002e
			public const int Magenta = 2131034158;
			
			// aapt resource value: 0x7f050071
			public const int Maroon = 2131034225;
			
			// aapt resource value: 0x7f05007b
			public const int MediumAquamarine = 2131034235;
			
			// aapt resource value: 0x7f050099
			public const int MediumBlue = 2131034265;
			
			// aapt resource value: 0x7f050056
			public const int MediumOrchid = 2131034198;
			
			// aapt resource value: 0x7f050065
			public const int MediumPurple = 2131034213;
			
			// aapt resource value: 0x7f050085
			public const int MediumSeaGreen = 2131034245;
			
			// aapt resource value: 0x7f050075
			public const int MediumSlateBlue = 2131034229;
			
			// aapt resource value: 0x7f050091
			public const int MediumSpringGreen = 2131034257;
			
			// aapt resource value: 0x7f050080
			public const int MediumTurquoise = 2131034240;
			
			// aapt resource value: 0x7f050052
			public const int MediumVioletRed = 2131034194;
			
			// aapt resource value: 0x7f05008c
			public const int MidnightBlue = 2131034252;
			
			// aapt resource value: 0x7f050036
			public const int MintCream = 2131034166;
			
			// aapt resource value: 0x7f05001d
			public const int MistyRose = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int Moccasin = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int NavajoWhite = 2131034144;
			
			// aapt resource value: 0x7f05009b
			public const int Navy = 2131034267;
			
			// aapt resource value: 0x7f050030
			public const int OldLace = 2131034160;
			
			// aapt resource value: 0x7f05006f
			public const int Olive = 2131034223;
			
			// aapt resource value: 0x7f050078
			public const int OliveDrab = 2131034232;
			
			// aapt resource value: 0x7f050025
			public const int Orange = 2131034149;
			
			// aapt resource value: 0x7f05002b
			public const int OrangeRed = 2131034155;
			
			// aapt resource value: 0x7f05004b
			public const int Orchid = 2131034187;
			
			// aapt resource value: 0x7f050040
			public const int PaleGoldenrod = 2131034176;
			
			// aapt resource value: 0x7f050063
			public const int PaleGreen = 2131034211;
			
			// aapt resource value: 0x7f05005b
			public const int PaleTurquoise = 2131034203;
			
			// aapt resource value: 0x7f050049
			public const int PaleVioletRed = 2131034185;
			
			// aapt resource value: 0x7f05001b
			public const int PapayaWhip = 2131034139;
			
			// aapt resource value: 0x7f050021
			public const int PeachPuff = 2131034145;
			
			// aapt resource value: 0x7f050050
			public const int Peru = 2131034192;
			
			// aapt resource value: 0x7f050023
			public const int Pink = 2131034147;
			
			// aapt resource value: 0x7f050046
			public const int Plum = 2131034182;
			
			// aapt resource value: 0x7f050059
			public const int PowderBlue = 2131034201;
			
			// aapt resource value: 0x7f050070
			public const int Purple = 2131034224;
			
			// aapt resource value: 0x7f05002f
			public const int Red = 2131034159;
			
			// aapt resource value: 0x7f050055
			public const int RosyBrown = 2131034197;
			
			// aapt resource value: 0x7f050083
			public const int RoyalBlue = 2131034243;
			
			// aapt resource value: 0x7f050068
			public const int SaddleBrown = 2131034216;
			
			// aapt resource value: 0x7f050034
			public const int Salmon = 2131034164;
			
			// aapt resource value: 0x7f05003a
			public const int SandyBrown = 2131034170;
			
			// aapt resource value: 0x7f050088
			public const int SeaGreen = 2131034248;
			
			// aapt resource value: 0x7f050019
			public const int Seashell = 2131034137;
			
			// aapt resource value: 0x7f050060
			public const int Sienna = 2131034208;
			
			// aapt resource value: 0x7f050053
			public const int Silver = 2131034195;
			
			// aapt resource value: 0x7f05006d
			public const int SkyBlue = 2131034221;
			
			// aapt resource value: 0x7f050079
			public const int SlateBlue = 2131034233;
			
			// aapt resource value: 0x7f050077
			public const int SlateGray = 2131034231;
			
			// aapt resource value: 0x7f050015
			public const int Snow = 2131034133;
			
			// aapt resource value: 0x7f05008f
			public const int SpringGreen = 2131034255;
			
			// aapt resource value: 0x7f050082
			public const int SteelBlue = 2131034242;
			
			// aapt resource value: 0x7f05004e
			public const int Tan = 2131034190;
			
			// aapt resource value: 0x7f050095
			public const int Teal = 2131034261;
			
			// aapt resource value: 0x7f05004c
			public const int Thistle = 2131034188;
			
			// aapt resource value: 0x7f05002a
			public const int Tomato = 2131034154;
			
			// aapt resource value: 0x7f050084
			public const int Turquoise = 2131034244;
			
			// aapt resource value: 0x7f050041
			public const int Violet = 2131034177;
			
			// aapt resource value: 0x7f050039
			public const int Wheat = 2131034169;
			
			// aapt resource value: 0x7f050011
			public const int White = 2131034129;
			
			// aapt resource value: 0x7f050037
			public const int WhiteSmoke = 2131034167;
			
			// aapt resource value: 0x7f050014
			public const int Yellow = 2131034132;
			
			// aapt resource value: 0x7f050061
			public const int YellowGreen = 2131034209;
			
			// aapt resource value: 0x7f05000a
			public const int aqua = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int black = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int blue = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int cellback = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int fuchsia = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int gray = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int green = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int lime = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int maroon = 2131034121;
			
			// aapt resource value: 0x7f05000f
			public const int navy = 2131034127;
			
			// aapt resource value: 0x7f050007
			public const int olive = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int purple = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int red = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int silver = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int teal = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int white = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int yellow = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int activity_horizontal_margin = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int activity_vertical_margin = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Selector = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int ListImage = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int ListItem = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int ListText1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int ListText2 = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int bodyText = 2131230725;
			
			// aapt resource value: 0x7f08000a
			public const int errorText = 2131230730;
			
			// aapt resource value: 0x7f080004
			public const int fragmentContainer = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int loginButton = 2131230731;
			
			// aapt resource value: 0x7f080009
			public const int passwordInput = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int passwordText = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int registerButton = 2131230732;
			
			// aapt resource value: 0x7f080006
			public const int username = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int usernameInput = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AppointmentList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int NotificationList = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int bodyText = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int loginButtonText = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int password = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int registerButtonText = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int username = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
