// <auto-generated />
namespace MediBook.Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class adding_doctor_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_doctor_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201404241802124_adding_doctor_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
