// <auto-generated />
namespace MediBook.Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class contact_number : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contact_number));
        
        string IMigrationMetadata.Id
        {
            get { return "201404290028410_contact_number"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
