// <auto-generated />
namespace MediBook.Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class updatinggcmfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatinggcmfield));
        
        string IMigrationMetadata.Id
        {
            get { return "201404231643531_updating-gcm-field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
